DjangoCRM/urls.py
from django.conf.urls import url,include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("app01.urls",namespace='app01')),
    url(r'^rbac/', include('rbac.urls',namespace='rbac')),
]

app01/urls.py
from django.conf.urls import url
from app01.views import *
urlpatterns = [
    url(r'^login/', Login.as_view(),name="login"),
    url(r'^logout/', Logout.as_view(),name="logout"),
    url(r'^register/', Register.as_view(),name="register"),
    #首页
    url(r'^home/', Home.as_view(),name="home"),
    #公户管理&我的客户
     url(r'^customers/', Customers.as_view(),name="customers"),
     url(r'^mycustomers/', Customers.as_view(),name="mycustomers"),
    #添加
     url(r'^customer/add/', AddOrEdit.as_view(),name="customer_add"),
     # url(r'^customer/add/', CustomerEditOrAdd.as_view(),name="customer_add"),
    #编辑
     url(r'^customer/edit/(-*\d+)/', AddOrEdit.as_view(),name="customer_edit"),
     # url(r'^customer/edit/(-*\d+)/', CustomerEditOrAdd.as_view(),name="customer_edit"),
     # url(r'^customer/edit/(\d+)/', CustomerEditOrAdd.as_view(),name="customer_edit"),
     #删除
     url(r'^customer/del/(-*\d+)/', CustomerDel,name="customer_del"),
    #跟进记录
     url(r'^consult_recode/list/', ConsultRecode.as_view(),name="consult_recode"),
    #编辑及添加跟进记录
     url(r'^consult_recode/edit/(-*\d+)/', AddOrEdit.as_view(),name="consult_recode_edit"),
     # url(r'^consult_recode/edit/(-*\d+)/', ConsultRecodeEditOrAdd.as_view(),name="consult_recode_edit"),
     # url(r'^consult_recode/add/', ConsultRecodeEditOrAdd.as_view(),name="consult_recode_add"),
     url(r'^consult_recode/add/', AddOrEdit.as_view(),name="consult_recode_add"),
    #删除
     url(r'^consult_recode/del/(-*\d+)/', ConsultRecodeDel,name="consult_recode_del"),


    #跟进记录
     url(r'^enrollment/list/', EnrollMent.as_view(),name="enrollment"),
    #编辑及添加跟进记录
     url(r'^enrollment/edit/(-*\d+)/', AddOrEdit.as_view(),name="enrollment_edit"),
     # url(r'^enrollment/edit/(-*\d+)/', EnrollMentEditOrAdd.as_view(),name="enrollment_edit"),
     # url(r'^enrollment/add/', EnrollMentEditOrAdd.as_view(),name="enrollment_add"),
     url(r'^enrollment/add/', AddOrEdit.as_view(),name="enrollment_add"),
    #删除
     url(r'^enrollment/del/(-*\d+)/', EnrollMentDel,name="enrollment_del"),



    #课程记录
     url(r'^courserecord/list/', CourseRecordView.as_view(),name="courserecord"),
    #编辑及添加课程记录
     url(r'^courserecord/edit/(-*\d+)/', AddOrEdit.as_view(),name="courserecord_edit"),
     url(r'^courserecord/add/', AddOrEdit.as_view(),name="courserecord_add"),
    #删除课程记录
     url(r'^courserecord/del/(-*\d+)/', CourseRecordDel,name="courserecord_del"),

    #学习记录展示
     url(r'^studyrecord/list/(-*\d+)/', StudyRecordView.as_view(),name="studyrecord"),
    # # 错误页面
    #  url(r'.*', error,name="error"),
]

rbac/urls.py
from django.conf.urls import url
from rbac.views import *

urlpatterns = [
    #角色页面
    url(r'^role/list/$', RoleList.as_view(),name='role_list'),
    url(r'^role/add/$', AddOrEdit.as_view(),name='role_add'),
    url(r'^role/edit/(\d+)/$', AddOrEdit.as_view(),name='role_edit'),
    url(r'^role/del/$',  RoleList.as_view(),name='role_del'),
    #菜单页面
    url(r'^menu/list/$', MenuList.as_view(),name='menu_list'),
    url(r'^menu/add/$', AddOrEdit.as_view(),name='menu_add'),
    url(r'^menu/edit/(\d+)/$', AddOrEdit.as_view(),name='menu_edit'),
    url(r'^menu/del/$', MenuList.as_view(),name='menu_del'),

    #权限编辑
    url(r'^access/add/$', AddOrEdit.as_view(),name='access_add'),
    url(r'^access/edit/(\d+)/$', AddOrEdit.as_view(),name='access_edit'),
    url(r'^access/del/$', MenuList.as_view(),name='access_del'),
    #批量编辑权限
    url(r'^access/list/$', AccessList.as_view(),name='access_list'),

    #权限分发
    url(r'^access/distribute/$', AccessDistribute.as_view(),name='access_distribute'),
    #测试用
    # url(r'^test/$', test,name='test'),

]

templates/sales/add_or_edit.html
{% extends 'starter.html' %}
{% load my_tags %}
{% block title %}
    {{ request.path|add_or_edit_title:form_id }}
{% endblock %}

{% block content %}
    <form class="form-horizontal" method="post" novalidate>
    {% csrf_token %}
        {% for field in modelform_obj %}
            <div class="form-group {% if field.errors.0 %}has-error{% endif %}">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-10">
                    {{ field }}
                    <span class="text-danger">{{ field.errors.0 }}</span>
                </div>
            </div>
        {% endfor %}


        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">保存</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/sales/consult_recode.html
{% extends 'starter.html' %}
{% load my_tags %}

{% block content %}
    <a href="{% url_encode request 'app01:consult_recode_add' %}" class="btn btn-primary">添加跟进记录</a>
    <form class="navbar-form navbar-left float-right" role="search" method="get">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <select class="form-control" name="search_model">
                    <option value="customer__name__icontains" {% if search_model == 'customer__name__icontains' %}
                            selected
                    {% endif %} >姓名
                    </option>
                </select>
            </div>
            <div>
                <input type="text" class="form-control" placeholder="Search" aria-label="Recipient's username"
                       aria-describedby="button-addon2" name="search_value" {% if search_value %}
                       value="{{ search_value }}"
                {% endif %} ></div>
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">搜索</button>
            </div>
        </div>
    </form>
    <form action="" method="post">
        {% csrf_token %}
        <table class="table table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>
                    <input type="checkbox" id="full-select">全选
                </th>
                <th>序号</th>
                <th>所咨询客户</th>
                <th>跟进内容</th>
                <th>跟进状态</th>
                <th>跟进人</th>
                <th>跟进日期</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for recode in all_consult_recode_filter %}
                <tr>
                    <td><input type="checkbox" name="selected" value="{{ recode.id }}"></td>
                    <td>{{ forloop.counter }}</td>
                    {#                <td>{{ request|list_number:forloop.counter }}</td>#}
                    <td>{{ recode.customer.name }}</td>
                    <td>{{ recode.note }}</td>
                    <td>{{ recode.get_status_display }}</td>
                    <td>{{ recode.consultant.username }}</td>
                    <td>{{ recode.date|date:"Y-m-d H:i:s" }}</td>
                    <td>
                        <a href="{% url_encode request 'app01:consult_recode_edit' recode.id %}" title="编辑"><i class="fa fa-pencil"></i>&nbsp;</a>
                        |<a href="{% url_encode request 'app01:consult_recode_del' recode.id all_consult_recode_filter|length %}" title="删除">&nbsp;<i class="fa fa-remove"></i></a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="10">当前无记录！</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
            <div class="col-sm-6">{{ page_html|safe }}</div>
            <div class="input-group mb-3 col-sm-3 offset-3">
                <div class="input-group-prepend col-sm-4 offset-4">
                    <select class="form-control" name="bulk_action">
                        <option value="bulk_del">删除</option>
                    </select>
                </div>
                <div class="input-group-append col-sm-4">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">批量操作</button>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

{% block jscode %}
    <script>
        $("#full-select").click(function () {
            if ($(this).prop('checked')) {
                $("[name='selected']").prop('checked', true);
            } else {
                $("[name='selected']").prop('checked', false);
            }
        });
    </script>
{% endblock %}

templates/sales/courserecode_list.html
{% extends 'starter.html' %}
{% load my_tags %}


{% block content %}
    <a href="{% url_encode request 'app01:courserecord_add' %}" class="btn btn-primary">添加课程记录</a>
    <form class="navbar-form navbar-left float-right" role="search" method="get">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <select class="form-control" name="search_model">
                    <option value="teacher__username__icontains" {% if search_model == 'teacher__username__icontains' %}
                            selected
                    {% endif %} >讲师姓名
                    </option>
                </select>
            </div>
            <div>
                <input type="text" class="form-control" placeholder="Search" aria-label="Recipient's username"
                       aria-describedby="button-addon2" name="search_value" {% if search_value %}
                       value="{{ search_value }}"
                {% endif %} ></div>
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">搜索</button>
            </div>
        </div>
    </form>
    <form action="" method="post">
        {% csrf_token %}
        <table class="table table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>
                    <input type="checkbox" id="full-select">全选
                </th>
                <th>序号</th>
                <th>节次</th>
                <th>上课日期</th>
                <th>本节课程标题</th>
                <th>本节课程内容</th>
                <th>班级</th>
                <th>讲师</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for recode in all_courser_recode_filter %}
                <tr>
                    <td><input type="checkbox" name="selected" value="{{ recode.id }}"></td>
                    <td>{{ forloop.counter }}</td>
                    {#                <td>{{ request|list_number:forloop.counter }}</td>#}
                    <td>{{ recode.day_num }}</td>
                    <td>{{ recode.date|date:'Y-m-d' }}</td>
                    <td>{{ recode.course_title }}</td>
                    <td>{{ recode.course_memo }}</td>
                    <td>{{ recode.re_class }}</td>
                    <td>{{ recode.teacher.username }}</td>
                    <td>
                        <a href="{% url 'app01:studyrecord' recode.id %}" title="查看学习记录"><i
                                class="fa fa-search-plus"></i>&nbsp;</a>
                        |
                        <a href="{% url_encode request 'app01:courserecord_edit' recode.id %}" title="编辑"><i
                                class="fa fa-pencil"></i>&nbsp;</a>
                        |<a href="{% url_encode request 'app01:courserecord_del' recode.id all_courser_recode_filter|length %}"
                            title="删除">&nbsp;<i class="fa fa-remove"></i></a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="10">当前无记录！</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
            <div class="col-sm-6">{{ page_html|safe }}</div>
            <div class="input-group mb-3 col-sm-3 offset-3">
                <div class="input-group-prepend col-sm-6 offset-2">
                    <select class="form-control" name="bulk_action">
                        <option value="bulk_create_studyrecord">生成学习记录</option>
                        {#                        <option value="bulk_del">删除</option>#}
                    </select>
                </div>
                <div class="input-group-append col-sm-4">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">批量操作</button>
                </div>
            </div>
        </div>
    </form>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">提示信息</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% if msg == 'filed' %}
                        添加失败,请勿重复添加！
                    {% endif %}
                    {% if msg == 'null' %}
                        添加失败,当前课程无学员！
                    {% endif %}
                    {% if msg == 'success' %}
                        添加成功！
                    {% endif %}
                    {% if msg == 'error' %}
                        添加失败,未知错误！
                    {% endif %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">知道了</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block jscode %}
    <script>
        $("#full-select").click(function () {
            if ($(this).prop('checked')) {
                $("[name='selected']").prop('checked', true);
            } else {
                $("[name='selected']").prop('checked', false);
            }
        });

        (function f() {
            var msg = '{{ msg }}';
            if (msg !== '') {
                $('#exampleModal').modal("toggle");
            }
        })();
    </script>
{% endblock %}

templates/sales/customer_list.html
{% extends 'starter.html' %}
{% load my_tags %}

{% block content %}
    <a href="{% url_encode request 'app01:customer_add' %}" class="btn btn-primary">添加客户</a>
    <form class="navbar-form navbar-left float-right" role="search" method="get">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <select class="form-control" name="search_model">
                    <option value="qq__icontains" {% if search_model == 'qq__icontains' %}
                            selected
                    {% endif %} >QQ
                    </option>
                    <option value="name__icontains" {% if search_model == 'name__icontains' %}
                            selected
                    {% endif %}>姓名
                    </option>
                </select>
            </div>
            <div>
                <input type="text" class="form-control" placeholder="Search" aria-label="Recipient's username"
                       aria-describedby="button-addon2" name="search_value" {% if search_value %}
                       value="{{ search_value }}"
                {% endif %} ></div>
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">搜索</button>
            </div>
        </div>
    </form>
    <form action="" method="post">
        {% csrf_token %}

        <table class="table table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>
                    <input type="checkbox" id="full-select">全选
                </th>
                <th>序号</th>
                <th>QQ</th>
                <th>姓名</th>
                <th>性别</th>
                <th>客户来源</th>
                <th>咨询课程</th>
                <th>状态</th>
                <th>销售</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in all_customers_filter %}
                <tr>
                    <td><input type="checkbox" name="selected" value="{{ customer.id }}"></td>
                    <td>{{ forloop.counter }}</td>
                    {#                <td>{{ request|list_number:forloop.counter }}</td>#}
                    <td>{{ customer.qq }}</td>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.get_sex_display }}</td>
                    <td>{{ customer.get_source_display }}</td>
                    <td>{{ customer.get_course_display }}</td>
                    <td {% if  customer.get_status_display == "未报名" %}
                        class="table-warning" {% else %}class="table-success"
                    {% endif %} >{{ customer.get_status_display }}</td>
                    <td>{{ customer.consultant.username|default:'暂无' }}</td>
                    <td>
                        {% if request.path|page_title == '私户信息展示' %}
                            <a href="{% url 'app01:consult_recode' %}?customer_id={{ customer.id }}" title="查看跟进信息"><i
                                class="fa fa-search-plus"></i>&nbsp;</a>
                        |
                        {% endif %}
                        <a href="{% url_encode request 'app01:customer_edit' customer.id %}" title="编辑"><i
                                class="fa fa-pencil"></i>&nbsp;</a>
                        |<a href="{% url_encode request 'app01:customer_del' customer.id all_customers_filter|length %}"
                            title="删除">&nbsp;<i
                            class="fa fa-remove"></i></a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="10">查询结果为空,请重新输入搜索条件！</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
            <div class="col-sm-6">{{ page_html|safe }}</div>
            <div class="input-group mb-3 col-sm-3 offset-3">
                <div class="input-group-prepend col-sm-4 offset-4">
                    <select class="form-control" name="bulk_action">
                        {% if request.path|page_title == '公户信息展示' %}
                            <option value="transfer_gs">公转私</option>
                        {% endif %}
                        {% if request.path|page_title == '私户信息展示' %}
                            <option value="transfer_sg">私转公</option>
                        {% endif %}
                    <option value="bulk_del">删除</option>
                    </select>
                </div>
                <div class="input-group-append col-sm-4">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">批量操作</button>
                </div>
            </div>
        </div>

    </form>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">提示信息</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% for name in msg %}
                        <tr>{{ name }},</tr>
                    {% endfor %}
                    这些用户已被其他销售选走！

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">知道了</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block jscode %}
    <script>
        $("#full-select").click(function () {
            if ($(this).prop('checked')) {
                $("[name='selected']").prop('checked', true);
            } else {
                $("[name='selected']").prop('checked', false);
            }
        });

        (function f() {
            var msg = '{{ msg }}';
            if (msg !== '') {
                {#confirm(msg);#}
                $('#exampleModal').modal("toggle");
            }
        })();
    </script>
{% endblock %}

templates/sales/enrollment_list.html
{% extends 'starter.html' %}
{% load my_tags %}
{% block title %}
    {{ request.path|customer_title }}
{% endblock title %}

{% block content %}
    <a href="{% url_encode request 'app01:enrollment_add' %}" class="btn btn-primary">添加报名记录</a>
    <form class="navbar-form navbar-left float-right" role="search" method="get">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <select class="form-control" name="search_model">
                    <option value="customer__name__icontains" {% if search_model == 'customer__name__icontains' %}
                            selected
                    {% endif %} >姓名
                    </option>
                </select>
            </div>
            <div>
                <input type="text" class="form-control" placeholder="Search" aria-label="Recipient's username"
                       aria-describedby="button-addon2" name="search_value" {% if search_value %}
                       value="{{ search_value }}"
                {% endif %} ></div>
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">搜索</button>
            </div>
        </div>
    </form>
    <form action="" method="post">
        {% csrf_token %}
        <table class="table table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>
                    <input type="checkbox" id="full-select">全选
                </th>
                <th>序号</th>
                <th>为什么报名</th>
                <th>具体期望</th>
                <th>审批通过</th>
                <th>客户名称</th>
                <th>school</th>
                <th>所报班级</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for recode in all_enrollment_recode_filter %}
                <tr>
                    <td><input type="checkbox" name="selected" value="{{ recode.id }}"></td>
                    <td>{{ forloop.counter }}</td>
                    {#                <td>{{ request|list_number:forloop.counter }}</td>#}
                    <td>{{ recode.why_us|default:'空' }}</td>
                    <td>{{ recode.your_expectation|default:'空' }}</td>
                    <td>{% if recode.contract_approved == True %}
                    是{% else %}否
                    {% endif %}</td>
                    <td>{{ recode.customer.name }}</td>
                    <td>{{ recode.school }}</td>
                    <td>{{ recode.enrolment_class }}</td>
                    <td>
                        <a href="{% url_encode request 'app01:enrollment_edit' recode.id %}" title="编辑"><i class="fa fa-pencil"></i>&nbsp;</a>
                        |<a href="{% url_encode request 'app01:enrollment_del' recode.id all_enrollment_recode_filter|length %}" title="删除">&nbsp;<i class="fa fa-remove"></i></a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="10">当前无记录！</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
            <div class="col-sm-6">{{ page_html|safe }}</div>
            <div class="input-group mb-3 col-sm-3 offset-3">
                <div class="input-group-prepend col-sm-4 offset-4">
                    <select class="form-control" name="bulk_action">
                        <option value="bulk_del">删除</option>
                    </select>
                </div>
                <div class="input-group-append col-sm-4">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">批量操作</button>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

{% block jscode %}
    <script>
        $("#full-select").click(function () {
            if ($(this).prop('checked')) {
                $("[name='selected']").prop('checked', true);
            } else {
                $("[name='selected']").prop('checked', false);
            }
        });
    </script>
{% endblock %}

templates/sales/studyrecode_list.html
{% extends 'starter.html' %}
{% load my_tags %}

{% block title %}
    {{ request.path|add_or_edit_title:form_id }}
{% endblock %}

{% block content %}
    <form class="navbar-form navbar-left float-right" role="search" method="get">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <select class="form-control" name="search_model">
                    <option value="customer__name__icontains" {% if search_model == 'customer__name__icontains' %}
                            selected
                    {% endif %} >姓名
                    </option>
                </select>
            </div>
            <div>
                <input type="text" class="form-control" placeholder="Search" aria-label="Recipient's username"
                       aria-describedby="button-addon2" name="search_value" {% if search_value %}
                       value="{{ search_value }}"
                {% endif %} ></div>
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">搜索</button>
            </div>
        </div>
    </form>
    {{ all_study_recode_filter.errors }}
    <form action="" method="post">
        {% csrf_token %}
        {{ all_study_recode_filter.management_form }}
        <table class="table table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>序号</th>
                <th>考勤</th>
                <th>本节成绩</th>
                <th>作业批语</th>
                <th>某节课程</th>
                <th>学员</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for recode in all_study_recode_filter %}
                <tr>
                    {{ recode.id }}
                    <td>{{ forloop.counter }}</td>
                    <td>{{ recode.attendance }}</td>
                    <td>{{ recode.score }}</td>
                    <td>{{ recode.homework_note }}</td>
                    <td>{{ recode.instance.course_record }}</td>
                    <td hidden>{{ recode.course_record }}</td>
                    <td>{{ recode.instance.student }}</td>
                    <td hidden>{{ recode.student }}</td>
                    <td>
                        <a href="" title="编辑"><i
                                class="fa fa-pencil"></i>&nbsp;</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="10">当前无记录！</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
            <div class="col-sm-6">{{ page_html|safe }}</div>
            <div class="input-group mb-3 col-sm-1 offset-5">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">保存</button>
            </div>
        </div>
    </form>

{% endblock %}

{% block jscode %}
    <script>
        $("#full-select").click(function () {
            if ($(this).prop('checked')) {
                $("[name='selected']").prop('checked', true);
            } else {
                $("[name='selected']").prop('checked', false);
            }
        });
    </script>
{% endblock %}