DjangoCRM/urls.py
from django.conf.urls import url,include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("app01.urls",namespace='app01')),
    url(r'^rbac/', include('rbac.urls',namespace='rbac')),
]

app01/urls.py
from django.conf.urls import url
from app01.views import *
urlpatterns = [
    url(r'^login/', Login.as_view(),name="login"),
    url(r'^logout/', Logout.as_view(),name="logout"),
    url(r'^register/', Register.as_view(),name="register"),
    #首页
    url(r'^home/', Home.as_view(),name="home"),
    #公户管理&我的客户
     url(r'^customers/', Customers.as_view(),name="customers"),
     url(r'^mycustomers/', Customers.as_view(),name="mycustomers"),
    #添加
     url(r'^customer/add/', AddOrEdit.as_view(),name="customer_add"),
     # url(r'^customer/add/', CustomerEditOrAdd.as_view(),name="customer_add"),
    #编辑
     url(r'^customer/edit/(-*\d+)/', AddOrEdit.as_view(),name="customer_edit"),
     # url(r'^customer/edit/(-*\d+)/', CustomerEditOrAdd.as_view(),name="customer_edit"),
     # url(r'^customer/edit/(\d+)/', CustomerEditOrAdd.as_view(),name="customer_edit"),
     #删除
     url(r'^customer/del/(-*\d+)/', CustomerDel,name="customer_del"),
    #跟进记录
     url(r'^consult_recode/list/', ConsultRecode.as_view(),name="consult_recode"),
    #编辑及添加跟进记录
     url(r'^consult_recode/edit/(-*\d+)/', AddOrEdit.as_view(),name="consult_recode_edit"),
     # url(r'^consult_recode/edit/(-*\d+)/', ConsultRecodeEditOrAdd.as_view(),name="consult_recode_edit"),
     # url(r'^consult_recode/add/', ConsultRecodeEditOrAdd.as_view(),name="consult_recode_add"),
     url(r'^consult_recode/add/', AddOrEdit.as_view(),name="consult_recode_add"),
    #删除
     url(r'^consult_recode/del/(-*\d+)/', ConsultRecodeDel,name="consult_recode_del"),


    #跟进记录
     url(r'^enrollment/list/', EnrollMent.as_view(),name="enrollment"),
    #编辑及添加跟进记录
     url(r'^enrollment/edit/(-*\d+)/', AddOrEdit.as_view(),name="enrollment_edit"),
     # url(r'^enrollment/edit/(-*\d+)/', EnrollMentEditOrAdd.as_view(),name="enrollment_edit"),
     # url(r'^enrollment/add/', EnrollMentEditOrAdd.as_view(),name="enrollment_add"),
     url(r'^enrollment/add/', AddOrEdit.as_view(),name="enrollment_add"),
    #删除
     url(r'^enrollment/del/(-*\d+)/', EnrollMentDel,name="enrollment_del"),



    #课程记录
     url(r'^courserecord/list/', CourseRecordView.as_view(),name="courserecord"),
    #编辑及添加课程记录
     url(r'^courserecord/edit/(-*\d+)/', AddOrEdit.as_view(),name="courserecord_edit"),
     url(r'^courserecord/add/', AddOrEdit.as_view(),name="courserecord_add"),
    #删除课程记录
     url(r'^courserecord/del/(-*\d+)/', CourseRecordDel,name="courserecord_del"),

    #学习记录展示
     url(r'^studyrecord/list/(-*\d+)/', StudyRecordView.as_view(),name="studyrecord"),
    # # 错误页面
    #  url(r'.*', error,name="error"),
]

rbac/urls.py
from django.conf.urls import url
from rbac.views import *

urlpatterns = [
    #角色页面
    url(r'^role/list/$', RoleList.as_view(),name='role_list'),
    url(r'^role/add/$', AddOrEdit.as_view(),name='role_add'),
    url(r'^role/edit/(\d+)/$', AddOrEdit.as_view(),name='role_edit'),
    url(r'^role/del/$',  RoleList.as_view(),name='role_del'),
    #菜单页面
    url(r'^menu/list/$', MenuList.as_view(),name='menu_list'),
    url(r'^menu/add/$', AddOrEdit.as_view(),name='menu_add'),
    url(r'^menu/edit/(\d+)/$', AddOrEdit.as_view(),name='menu_edit'),
    url(r'^menu/del/$', MenuList.as_view(),name='menu_del'),

    #权限编辑
    url(r'^access/add/$', AddOrEdit.as_view(),name='access_add'),
    url(r'^access/edit/(\d+)/$', AddOrEdit.as_view(),name='access_edit'),
    url(r'^access/del/$', MenuList.as_view(),name='access_del'),
    #批量编辑权限
    url(r'^access/list/$', AccessList.as_view(),name='access_list'),

    #权限分发
    url(r'^access/distribute/$', AccessDistribute.as_view(),name='access_distribute'),
    #测试用
    # url(r'^test/$', test,name='test'),

]

templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>路径错误</h1>
</body>
</html>

templates/home.html
{% extends 'starter.html' %}

{% block title %}
首页展示
{% endblock %}

{% block content %}
<h1>欢迎{{ request.session.username }}来到MyCrm</h1>
{% endblock %}

templates/starter.html
{% load static %}
{% load my_tags %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>MyCrm</title>

    <!-- Font Awesome Icons -->

    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.css' %}">

    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'rbac/css/menu.css' %} "/>
    <style>
        .table tbody tr td {
            vertical-align: middle;
            text-align: center;
        }

        .table th {
            text-align: center;
        }

    </style>
    {% block style %}

    {% endblock style %}
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="#" class="nav-link">Home</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="#" class="nav-link">Contact</a>
            </li>
        </ul>

        <!-- SEARCH FORM -->
        <form class="form-inline ml-3">
            <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-navbar" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </form>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <!-- Messages Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-comments"></i>
                    <span class="badge badge-danger navbar-badge">3</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="{% static 'dist/img/user1-128x128.jpg' %}" alt="User Avatar"
                                 class="img-size-50 mr-3 img-circle">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Brad Diesel
                                    <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">Call me whenever you can...</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="{% static 'dist/img/user8-128x128.jpg' %}" alt="User Avatar"
                                 class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    John Pierce
                                    <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">I got your message bro</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="{% static 'dist/img/user3-128x128.jpg' %}" alt="User Avatar"
                                 class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Nora Silvester
                                    <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">The subject goes here</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                </div>
            </li>
            <!-- Notifications Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-bell"></i>
                    <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header">15 Notifications</span>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-envelope mr-2"></i> 4 new messages
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-users mr-2"></i> 8 friend requests
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-file mr-2"></i> 3 new reports
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#"><i
                        class="fas fa-th-large"></i></a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="javascript: void (0);" class="brand-link">
            <img src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo"
                 class="brand-image img-circle elevation-3"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">MyCrm</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2"
                         alt="User Image">
                </div>
                <div class="info">
                    <a href="{% url 'app01:home' %}" class="d-block">{{ request.session.username }}</a>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                    <!--左侧菜单栏引入-->
                    {% include 'rbac/menu.html' %}

                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">
                            {% block title %}
                                {{ request.path|page_title }}
                            {% endblock title %}
                        </h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        {% include 'rbac/bread_crumb.html' %}
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            {% block content %}

            {% endblock content %}
        </div>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
        <div class="p-3">
            <h5>个人中心</h5>
            <p><a href="{% url 'app01:logout' %}">注销</a></p>
        </div>
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
            Anything you want
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
    </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'jquery.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>

<!--rbac -->
{#<script src="{% static 'rbac/js/menu_control.js' %}"></script>#}
<script src="{% static 'rbac/js/table_control.js' %}"></script>
</body>

<script>
    (function () {
        var a = $('[auth]');
        var allowed = {{ request.button_url|safe }};
        for (var i = 0; i < a.length; ++i) {
            var href = a.eq(i).attr('href');
            var target = i;
            var count = 0;
            for (var url of allowed) {
                var patt = url.url;
                var pattern = new RegExp(patt);
                if (pattern.exec(href) === null) {
                    count++;
                }
            }
            if (count === allowed.length) {
                a.eq(target).remove();
            }

        }
    })();
</script>
{% block jscode %}

{% endblock jscode %}
</html>